---
- name: Destroy EC2 instance(s)
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - amazon.aws

  vars:
    region: eu-central-1
    role_tag_key: Role
    role_tag_value: molecule-nginx-test
    name_prefixes: ["molecule-nginx-test-"]
    molecule_instance_config: "{{ lookup('env', 'MOLECULE_INSTANCE_CONFIG') | default('/tmp/molecule_instance_config.yml', true) }}"

  tasks:
    - name: Stat instance_config.yml
      ansible.builtin.stat:
        path: "{{ molecule_instance_config }}"
      register: ic_stat

    - name: Read instance_config.yml when present
      ansible.builtin.slurp:
        path: "{{ molecule_instance_config }}"
      register: instance_conf_raw
      when: ic_stat.stat.exists

    - name: Parse instance configuration
      ansible.builtin.set_fact:
        instance_conf: "{{ instance_conf_raw.content | b64decode | from_yaml | default([]) }}"
      when: ic_stat.stat.exists

    - name: Collect instance IDs from file (if any)
      ansible.builtin.set_fact:
        ids_from_file: "{{ instance_conf | map(attribute='instance_id') | select('defined') | list }}"
      when: ic_stat.stat.exists

    - name: Lookup instances by Role tag
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:{{ role_tag_key }}": "{{ role_tag_value }}"
          instance-state-name:
            - pending
            - running
            - stopping
            - stopped
      register: ec2_by_role

    - name: Collect IDs from Role tag lookup
      ansible.builtin.set_fact:
        ids_from_role: "{{ ec2_by_role.instances | map(attribute='instance_id') | list | default([]) }}"

    - name: List all instances in region (broad safety net)
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
      register: ec2_all

    - name: Filter instances locally by Role tag (and optional Name prefixes)
      ansible.builtin.set_fact:
        ids_from_local_filter: >-
          {{
            ec2_all.instances
            | selectattr('tags', 'defined')
            | selectattr('tags.' ~ role_tag_key, 'defined')
            | selectattr('tags.' ~ role_tag_key, 'equalto', role_tag_value)
            | selectattr('tags.Name', 'defined')
            | selectattr('tags.Name', 'search', '(' ~ (name_prefixes | map('regex_escape') | join('|')) ~ ')')
            | map(attribute='instance_id')
            | list
          }}

    - name: Compute final list of instance IDs to terminate
      ansible.builtin.set_fact:
        instance_ids_to_terminate: >-
          {{
            (
              (ids_from_file | default([]))
              + (ids_from_role | default([]))
              + (ids_from_local_filter | default([]))
            ) | unique
          }}

    - name: Show what will be terminated
      ansible.builtin.debug:
        msg: "Terminating instances: {{ instance_ids_to_terminate | default([]) }}"

    - name: Terminate instances (if any)
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_ids_to_terminate }}"
        state: absent
        wait: true
      when: instance_ids_to_terminate | length > 0

    - name: Remove Molecule instance config file
      ansible.builtin.file:
        path: "{{ molecule_instance_config }}"
        state: absent
